adminUser:
  password: local:ferocious-unicorn-1592929006/adminUser:password
  username: admin
docker:
  email: ablazleon@gmail.com
  password: local:ferocious-unicorn-1592929006/docker:password
  url: https://hub.docker.com/
  username: ablazleon
enableDocker: true
pipelineUser:
  email: ablazleon@gmail.com
  token: local:ferocious-unicorn-1592929006/pipelineUser:token
  username: ablazleon
prow:
  hmacToken: local:ferocious-unicorn-1592929006/prow:hmacToken
